export const GET_POSTCODE_DATA = 'GET_POSTCODE_DATA';
export const SET_POSTCODE_ERROR = 'SET_POSTCODE_ERROR';
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR';
